# services:
#   - type: web
#     name: opensign-server
#     runtime: image
#     plan: free

#     image:
#       url: docker.io/opensign/opensignserver:main

#     # Optional but recommended
#     # dockerCommand: node server.js   # only if needed

#     envVars:
#       - key: NODE_ENV
#         value: production

#       - key: PUBLIC_URL
#         value: "https://opensign-server-rjna.onrender.com"

#       - key: SERVER_URL
#         value: "https://opensign-server-rjna.onrender.com/api/app"

#       - key: PARSE_MOUNT
#         value: /api/app

#       # Secrets / values you'll fill in the dashboard
#       - key: MONGODB_URI
#         sync: false

#       - key: DO_SPACE
#         sync: false

#       - key: DO_ENDPOINT
#         sync: false

#       - key: DO_BASEURL
#         sync: false

#       - key: DO_ACCESS_KEY_ID
#         sync: false

#       - key: DO_SECRET_ACCESS_KEY
#         sync: false

#       - key: DO_REGION
#         value: auto

#       - key: USE_LOCAL
#         value: "false"

services:
  - type: web
    name: opensign-server
    runtime: image
    plan: free

    image:
      url: docker.io/opensign/opensignserver:main

    envVars:
      - key: NODE_ENV
        value: production

      - key: PUBLIC_URL
        value: "https://opensign-dashboard.onrender.com"

      - key: SERVER_URL
        value: "https://opensign-server-rjna.onrender.com/api/app"

      - key: PARSE_MOUNT
        value: /api/app

      - key: MASTER_KEY
        sync: false

      - key: MONGODB_URI
        sync: false

      - key: DO_SPACE
        sync: false

      - key: DO_ENDPOINT
        sync: false

      - key: DO_BASEURL
        sync: false

      - key: DO_ACCESS_KEY_ID
        sync: false

      - key: DO_SECRET_ACCESS_KEY
        sync: false

      - key: DO_REGION
        value: auto

      - key: USE_LOCAL
        value: "false"

  - type: web
    name: opensign-dashboard
    runtime: image
    plan: free

    image:
      url: docker.io/opensign/opensign:main

    envVars:
      - key: NODE_ENV
        value: production

      - key: REACT_APP_SERVERURL
        value: "https://opensign-server-rjna.onrender.com/api/app"

      - key: PUBLIC_URL
        value: "https://opensign-dashboard.onrender.com"
